### PR TITLE
SA-3048 Adhoc inference script

### PR DESCRIPTION
**Pull request by MJafarMashhadi**
Testing locally:

```python
docker-compose exec annotation_server python alchemy/scripts/manual_inference_api_invocation.py data.jsonl -u http://admin_server:5000/api/trigger_inference --token-from-env
```

Running on production:
```python
docker-compose -f docker-compose-staging.yml exec annotation_server python alchemy/scripts/manual_inference_api_invocation.py data.jsonl -u /admin/api/trigger_inference 
```

you can conveniently run it from your local dev environment in a one liner:

```bash
gcloud compute ssh blah --command="bash -c 'cd /var/www && docker-compose ...'"
```

To see the available datasets head over to the dataset menu in the Admin server.

### CODE REVIEW

**Review by jzhang-gp — APPROVED** [review]
LGTM. In the PR description, let's try not to include Georgian specific comments (i.e., links and urls). If we need to, mask it if possible.

**Comment by balmasi** [comment]
Task linked: [SA-3048 As the SA website, I want to trigger adhoc inference on Alchemy models. This requires integration work involve API calls and permissions.](https://app.clickup.com/t/1236149/SA-3048)

**Comment by balmasi** [comment]
Task linked: [SA-3149 As a website user I want the log in link to work both on /admin and /](https://app.clickup.com/t/1236149/SA-3149)

**Review by dhuang-gp — APPROVED** [review]

**Comment by MJafarMashhadi** [comment]
Thanks @jzhang-gp @dhuang-gp

**Pull request merged**
