### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by MJafarMashhadi**

### CODE REVIEW

**Comment by MJafarMashhadi** [comment]
TODO: rebase and clean up the commits before taking this out of draft status.

**Comment by MJafarMashhadi** [comment]
Any ideas on why `test_train_flow.py` tests fail?

**Comment by MJafarMashhadi** [comment]
Thanks @jzhang-gp, hardcoding the worker OS version in 172b61c fixed the issue!

ref: https://stackoverflow.com/questions/63034846/python-sqlite3-success-on-local-but-failed-on-github-action

**Review by jzhang-gp — APPROVED** [review]
LGTM!

**Pull request merged**
