### PR TITLE
Cloud build training image

### PR DESCRIPTION
**Pull request by MJafarMashhadi**
Created a trigger on GCP that only builds the training image if relevant files are changed in a commit to main branch.

### CODE REVIEW

**Comment by jzhang-gp** [comment]
How does this cloudbuild file alone detects that the changes are for the training image?

**Comment by MJafarMashhadi** [comment]
Set it to trigger if both conditions are true:
- push is on a branch matching `/^master$/`
- a change in `alchemy/train/no_deps/**` is detected

**Comment by jzhang-gp** [comment]
> Set it to trigger if both conditions are true:
> 
>     * push is on a branch matching `/^master$/`
> 
>     * a change in `alchemy/train/no_deps/**` is detected

So the trigger is on Cloud build console, correct? There is no code changes involving that, right?

**Comment by MJafarMashhadi** [comment]
> > Set it to trigger if both conditions are true:
> > ```
> > * push is on a branch matching `/^master$/`
> > 
> > * a change in `alchemy/train/no_deps/**` is detected
> > ```
> 
> So the trigger is on Cloud build console, correct? There is no code changes involving that, right?

Correct. Referring to the comment on #159 , it would be better to have that config it in the codebase itself

**Comment by jzhang-gp** [comment]
> > > Set it to trigger if both conditions are true:
> > > ```
> > > * push is on a branch matching `/^master$/`
> > > 
> > > * a change in `alchemy/train/no_deps/**` is detected
> > > ```
> > 
> > 
> > So the trigger is on Cloud build console, correct? There is no code changes involving that, right?
> 
> Correct. Referring to the comment on #159 , it would be better to have that config it in the codebase itself

Yeah that make sense. Could you add a comment in the cloud build file to explain the conditions and they are currently specified in the cloud build console?

**Review by jzhang-gp — APPROVED** [review]
As mentioned in the discussion, let's temporarily add a comment to explain the conditions and where they are specified.

**Comment by MJafarMashhadi** [comment]
> As mentioned in the discussion, let's temporarily add a comment to explain the conditions and where they are specified.

Added, also added some details in confluence page "CI/CD Pipeline Roadmap"

**Pull request merged**
