### PR TITLE
Address the comments in review

### PR DESCRIPTION
**Pull request by MJafarMashhadi**

### CODE REVIEW

**Review by jzhang-gp — COMMENTED** [review]
Have you tested triggering the training process?

**Comment by MJafarMashhadi** [comment]
> Have you tested triggering the training process?

I haven't, do you have an example file handy that I can use? If you don't I will download some data myself and test it

**Comment by MJafarMashhadi** [comment]
> > Have you tested triggering the training process?
> 
> I haven't, do you have an example file handy that I can use? If you don't I will download some data myself and test it

Still works, nothing is broken

**Review by jzhang-gp — APPROVED** [review]
LGTM

**Pull request merged**
